### ISSUE TITLE
Missing search-field under "Mitgliedsbeitrag"

### ISSUE THREAD

**Issue by 100user** [rmbinder/Mitgliedsbeitrag#100]
Since update 5.1.1 i am missing the "search" field at the top of the list.

![Unbenannt](https://user-images.githubusercontent.com/100995032/156877451-cd770486-8b13-40fd-9502-45c91ff0f400.JPG)

**Comment by rmbinder** [comment]
The "search" field should appear. 

What is it like when lists are displayed via "Groups & Roles". Is the "search" field there also missing?

**Comment by 100user** [comment]
Jetzt, nachdem ich im Browser den Cache gelöscht habe funktioniert es wieder. Danke für die schnelle Antwort.
Sie können das Ticket wieder schliessen.
