### ISSUE TITLE
Pre_Notification: same mail content to multiple members

### ISSUE THREAD

**Issue by rmbinder** [rmbinder/Mitgliedsbeitrag#102]
If pre-notification information is to be sent to several members in the pre_notification.php module (via the checkboxes), the data of the first member is sent to all other members.

[https://www.admidio.org/forum/viewtopic.php?f=10&t=9168](https://www.admidio.org/forum/viewtopic.php?f=10&t=9168)

**Comment by sielnet** [comment]
Mit der aktuelen Admidio Version und der aktuellen Version des Plugins tritt der Fehler immer noch auf.
Ich hatte vor ein paar tagen geupdated.

Vorher hat dein Fix geholfen, dieser war manuel eingespielt.
Jetzt allerdings mit dein Dateinen von Admidio und Mitgliedsbeiträge ohne eigenen Änderungen ist der Fehler wieder da.

**Comment by rmbinder** [comment]
Der Fix kommt mit Plugin-Version 5.1.3.
Ich möchte zuerst noch Issue 101 abarbeiten, dann erst werde ich eine neue Version veröffentlichen.
Bis dahin muss die message_send.php immer manuell eingespielt werden.

Eine andere Möglichkeit wäre, den Master hier von GitHub herunterzuladen. Das ist im Prinzip die Version 5.1.2 + der geänderten message_send.php.
