### ISSUE TITLE
Export-Fälligkeitsdatum listet keine Mitglieder

### ISSUE THREAD

**Issue by XMol** [rmbinder/Mitgliedsbeitrag#104]
Hallo,

wir haben admidio jetzt ein Jahr bei uns im Einsatz und nun möchten wir die Beiträge für 2022 einziehen. Um eine SEPA-Datei zu exportieren müssen (neue) Fälligkeitsdaten gesetzt werden/sein. Das Problem ist, ich sehe keine Möglichkeit dafür.

Wenn ein Mitglied unter &rarr;Beiträge-Beitragszahlungen abgehakt wird, dann verschwindet das Fälligkeitsdatum. Nur Mitglieder dessen Beitrag noch nicht bezahlt wurde werden unter &rarr;Beiträge-Export-Falligkeitsdatum gelistet - aktuell niemand, weil alle Beiträge eingezogen worden sind bzw. kein Mitglied noch ein Fälligkeitsdatum hat. Und weil niemand aufgelistet wird kann ich für niemanden ein neues Fälligkeitsdatum setzen.

Ich könnte für *einzelne* Mitglieder ein neues Fälligkeitsdatum einstellen, indem ich die jeweiligen Informationen editiere. Für über 100 Personen ist mir das allerdings zu viel Aufwand. 🙂 

Fehlen mir womöglich bestimmte Rechte in admidio? Stimmt etwas mit unserer Datenstruktur nicht? Haben wir etwas in falscher Reihenfolge gemacht?

Zunächst dachte ich, wir müssten die Beiträge für alle Mitglieder neu berechnen lassen (&rarr;Beiträge-Neuberechnung). Allerdings vermute ich, das ist nur notwendig wenn der Beitragssatz oder die Gruppen/Rollen in admidio verändert wurden?

Mit freundlichen Grüßen,
Xavier Mol.

/cc @luebbe

**Comment by rmbinder** [comment]
So wie es aussieht, hast Du das **Bezahlt-Datum** nicht gelöscht. 
Lösche mal testweise bei einem Mitglied das "Bezahlt-Datum". Dieses Mitglied sollte jetzt unter →Beiträge-Export-Falligkeitsdatum angezeigt werden.

Der normale Ablauf sollte so sein:

1. Beiträge berechnen
2. Fälligkeitsdatum setzen
3. SEPA-XML-Datei erzeugen
4. über Homebanking-Programm (extern) Beiträge einziehen
5. Bezahlt-Datum setzen

kommen während des Jahres neue Mitglieder hinzu, wieder von vorne (bei Punkt 1)  beginnen

- am Ende eines Jahres, bzw. vor dem nächsten Gesamtjahreseinzug "Löschen" (und zwar alles: Bezahlt-Datum, Beitrag, Fälligkeitsdatum usw)
- über Einstellungen - Beitragseinstellungen das Präfix ändern, in z.B. Mitgliedsbeitrag 2022"
- wenn mit altersgestaffelten Rollen gearbeitet wird: "Neuzuordnung altersgestaffelte Rollen" ausführen
- jetzt wieder bei Punkt 1. beginnen

**Comment by luebbe** [comment]
Ah, ok. Es gibt also intern nur ein Bezahlt Datum. Man kann also demzufolge auch nur einen offenen Posten pro Person verfolgen. Ist das nicht ein bisschen knapp? Wie soll man säumige Zahler im Blick behalten? Mitglieder die spät im Jahr beitreten können ja durchaus die alte Rechnung von 2021 und die neue Rechnung von 2022 offen haben, ohne säumig zu sein.
Ich hatte das bei unserem alten System so gelöst, dass pro Rechnungslauf ein Datensatz pro zahlungspflichtiger Person erzeugt wird. In der Übersicht "Bezahlt" konnte eine Person also mehrfach auftauchen und der Kassierer muss dann eben anhand des Überweisungsbelegs an der richtigen Stelle das Häkchen für "bezahlt" setzen.

**Comment by XMol** [comment]
@luebbe stellt die richtigen Fragen. 🙂 Aktuell haben wir zwei Mitglieder die kein Bezahlt-Datum haben. Für einen von ihnen würden wir gerne den ausstehenden Beitrag von 2021 erhalten und trotzdem schon die Beitragszahlungen für 2022 anstoßen (der andere passt so gar nicht ins System und deswegen ignorieren wir ihn diesmal).

Beide haben auch _kein_ Fälligkeitsdatum, weswegen sie nicht unter &rarr;Beiträge-Export-Fälligkeitsdatum auftauchen. Das Bezahlt-Datum für weitere Mitglieder zu löschen sollte in denselben Zustand führen, richtig?

**Comment by rmbinder** [comment]
> Das Bezahlt-Datum für weitere Mitglieder zu löschen sollte in denselben Zustand führen, richtig?


- Wenn die Mandatsdaten vollständig sind (Mandats-ID + Mandatsdatum)
- und eine IBAN vorhanden ist
- und ein Beitrag errrechnet wurde
- und KEIN Bezahlt-Datum gesetzt ist,
- dann werden die Mitglieder unter →Beiträge-Export-Fälligkeitsdatum angezeigt und man kann ein Fälligkeitsdatum setzen

Das Problem mit den offenen Posten pro Person (Rechnung 2021, Rechnung 2022) kann ich nachvollziehen. Eine Umsetzung ist aber bei der derzeitigen Auslegung des Plugins leider nicht möglich. Ein errechneter Beitrag wird im Profil eines Mitglieds in einem Profilfeld gespeichert. Diese Profilfeld ist einmal vorhanden, also kann auch nur ein Beitrag gespeichert werden.
Ich müsste das Plugin grundlegend überarbeiten und alle Rechnungen (Beitrag, Beitragstext, Fälligkeitsdatum usw) in einer eigenen Tabelle speichern (und nicht mehr im Profil eines Mitglieds). Ich habe das mal auf meine toDo-Liste gesetzt. Wenn ich eine Möglichkeit sehe, erzeuge ich einen Issue.
Vorher, und das steht ganz oben auf meiner Liste, werde ich die Dokumentation auf aktuellen Stand bringen (inkl. einer englischen Übersetzung) und das wird einige Zeit in Anspruch nehmen..

**Comment by luebbe** [comment]
Danke für die Antwort!

**Comment by rmbinder** [comment]
Vorschlag:

Bei den Mitgliedern, bei denen die Zahlung von 2021 noch aussteht, die Daten nicht löschen, sondern eine Neuberechnung mit der Option "Aufsummieren" durchführen. Dadurch wird eine neuer Beitrag errechnet und zum bestehenden Betrag hinzuaddiert.

**Comment by XMol** [comment]
Aufsummieren gilt dann automatisch nicht für die Mitglieder die ihren Beitrag gezahlt haben? Der Punkt an dem alles ("Bezahlt-Datum, Beitrag, Fälligkeitsdatum usw") gelöscht werden soll wird dafür ausgelassen? Das wäre ja schon fast genau das was wir haben wollten. Wir verlieren zwar eine eindeutige Zuordnung der Beiträge zu Kalenderjahren, aber solange die Summe stimmt wäre ich damit zufrieden.

**Comment by rmbinder** [comment]
> Aufsummieren gilt dann automatisch nicht für die Mitglieder die ihren Beitrag gezahlt haben?

War bisher nicht, habe ich gerade geändert (Änderung ist im aktuellen Master)

> Der Punkt an dem alles ("Bezahlt-Datum, Beitrag, Fälligkeitsdatum usw") gelöscht werden soll wird dafür ausgelassen?

Im Prinzip ja. Einfach mal testen. Eine Neuberechnung schreibt ja nicht sofort in die DB, das Ergebnis wird erst angezeigt. Wenn man nicht "Speichern" drückt, ist nichts passiert.

 

> Wir verlieren zwar eine eindeutige Zuordnung der Beiträge zu Kalenderjahren...

Wenn unter ->Einstellungen-Beitragseinstellungen im Präfix das Jahr mit angegeben wird, z.B. Mitgliedsbeitrag 2022, dann erscheint dieser Text bei Verwendung der Option "Aufsummieren" auch im Beitragstext.

**Comment by XMol** [comment]
Ich kann jetzt bestätigen, dass man nach dem Löschen neue Fälligkeitsdaten setzen und anschließend SEPA- und Rechnungsdateien exportieren kann.

**Comment by luebbe** [comment]
Habe soeben auf die neueste Version aktualisiert. Wir testen dann auch #103.

**Comment by rmbinder** [comment]
Ich habe jetzt 3 Issues umgesetzt, die auch Auswirkungen auf Eure Fragen haben:

#106: Wenn man das "Bezahlt-Datum" (nach einem großen Beitragseinzug) für viele Mitglieder setzen will, einige wenige aber nicht bezahlt haben, ist es jetzt möglich, im Modul Beitragszahlen diese "einige wenige" abzuwählen (damit kein "Bezahlt-Datum" für sie gesetzt wird).

#105: Im nächsten Schritt kann dann eine Neuberechnung mit den Optionen "nicht bezahlt" und "Aufsummieren" durchgeführt werden.  Dadurch wird nur für die, die noch nicht bezahlt haben, ein Beitrag berechnet und hinzuaddiert.

#107: Nach einer Neuberechnung gibt es eine Vorschau (zu diesem Zeitpunkt ist noch nichts in der DB gespeichert). Hier kann man jetzt den neuen Beitrag (und auch Beitragstext) anklicken und vor dem Speichern nochmal korrigieren.

**Comment by XMol** [comment]
Das klingt durch die Bank sehr gut! 👍 Noch sind wir nicht dazu gekommen Beiträge für 2022 einzuziehen, also werden wir Gelegenheit haben diese neuen Features auszutesten.

**Comment by rmbinder** [comment]
> Seltsam ist, dass die versendete Nachricht in admidio den Parameter #recipient# nicht aufgelöst hat.

Der Parameter #recipients# (wie auch #sender# oder #message#) wird in einem HTML-EMail-Template verwendet. Mitgliedsbeitrag verwendet diese Parameter aber nicht, bzw. sie werden automatisch "übersetzt".  

> Es ist etwas befremdlich, dass man das Format für den Export der Rechnungen auswählt, bevor man...

Wird diese Auswahl eigentlich benutzt? Ich persönlich verwende, seit es die Option XLSX gibt, nur noch das Excel-Format. Wenn nicht, packe ich diese Auswahl in das Einstellungen-Menü.

> Ausserdem ist der vorgeschlagene Dateiname immer rechnung.csv...

Unter Einstellungen-Export-Rechnung ist hier immer noch "rechnung.csv" eingestellt. Einfach ändern auf "rechnung". Dann passt der Dateiname.

> Soweit ich es der Dokumentation entnehmen konnte gibt es keinen Parameter um den Namen des Mitglieds...

Es können alle Parameter verwendet werden, die unter Einstellungen-Beitragseinstellungen-Beitragszahlungen E-Mail-Text aufgeführt sind. Hier werde ich die Doku noch ändern.

**Comment by XMol** [comment]
Um dieses Issue nicht noch weiter mit anderen Themen zu vermischen schließe ich es jetzt.
