### ISSUE TITLE
SEPA-Dateiformat ist inkorrekt

### ISSUE THREAD

**Issue by XMol** [rmbinder/Mitgliedsbeitrag#108]
Hallo @rmbinder 

leider scheint die generierte SEPA-Datei nicht mehr ganz korrekt zu sein:
![grafik](https://user-images.githubusercontent.com/14311469/165973445-ba66ca6c-7a9b-4ef5-9015-cc6802244012.png)

Auch das Onlinebanking der Sparkasse beschwert sich:
> Das verwendete Dateiformat wird nicht unterstützt. Unterstützte Dateiformate für Lastschriften PAIN 008.001.02, PAIN 008.003.02, für Überweisungen PAIN 001.003.03, PAIN 001.001.03, PAIN 001.001.08.

Hier ein zensierter Auszug aus der SEPA-Datei:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<Document xmlns='urn:iso:std:iso:20022:tech:xsd:pain.008.001.02' 
    		xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
    		xsi:schemaLocation='urn:iso:std:iso:20022:tech:xsd:pain.008.001.02 pain.008.001.02.xsd'>
<CstmrDrctDbtInitn>
<GrpHdr>
<MsgId>Message-ID-BCS</MsgId>
<CreDtTm>2022-04-29T16:33:09.000Z</CreDtTm>
<NbOfTxs>48</NbOfTxs>
<CtrlSum>5216</CtrlSum>
<InitgPty>
<Nm>Badminton Club Spoeck 1995 e.V.</Nm>
</InitgPty>
</GrpHdr>
<PmtInf>
<PmtInfId>Beitragszahlungen</PmtInfId>
<PmtMtd>DD</PmtMtd>
<BtchBookg>true</BtchBookg>
<NbOfTxs>48</NbOfTxs>
<CtrlSum>5216</CtrlSum>
<ReqdColltnDt>2022-05-02</ReqdColltnDt>
<Cdtr>
<Nm>Badminton Club Spoeck 1995 e.V.</Nm>
</Cdtr>
<CdtrAcct>
<Id>
<IBAN>...</IBAN>
</Id>
</CdtrAcct>
<CdtrAgt>
<FinInstnId>
<BIC>...</BIC>
</FinInstnId>
</CdtrAgt>
<ChrgBr>SLEV</ChrgBr>
<CdtrSchmeId>
<Id>
<PrvtId>
<Othr>
<Id>...</Id>
<SchmeNm>
<Prtry>SEPA</Prtry>
</SchmeNm>
</Othr>
</PrvtId>
</Id>
</CdtrSchmeId>
<DrctDbtTxInf>
<PmtId>
<EndToEndId>BCS-3-2022-04-29</EndToEndId>
</PmtId>
<PmtTpInf>
<SvcLvl>
<Cd>SEPA</Cd>
</SvcLvl>
<LclInstrm>
<Cd>CORE</Cd>
</LclInstrm>
<SeqTp>RCUR</SeqTp>
</PmtTpInf>
<InstdAmt Ccy="EUR">120</InstdAmt>
<DrctDbtTx>
<MndtRltdInf>
<MndtId>...</MndtId>
<DtOfSgntr>1995-10-30</DtOfSgntr>
<AmdmntInd>false</AmdmntInd>
</MndtRltdInf>
</DrctDbtTx>
<DbtrAgt>
<FinInstnId>
<BIC>...</BIC>
</FinInstnId>
</DbtrAgt>
<Dbtr>
<Nm>Albert Schweizer</Nm>
</Dbtr>
<DbtrAcct>
<Id>
<IBAN>...</IBAN>
</Id>
</DbtrAcct>
<RmtInf>
<Ustrd>Beitrag in 2022 fuer Mitglieder ab dem vollendeten 18. Lebensjahr</Ustrd>
</RmtInf>
</DrctDbtTxInf>
</PmtInf>
</CstmrDrctDbtInitn>
</Document>
```

Ich kann leider nicht genau sagen welche Version wir verwenden, da ich nicht der Administrator bin. Es sollte diejenige sein, die [vor vier Tagen die Neueste war](https://github.com/rmbinder/Mitgliedsbeitrag/issues/104#issuecomment-1108920827).

/cc @luebbe

**Comment by XMol** [comment]
Ich habe versucht die generierte SEPA-Datei gegen das Schema pain.008.001.02 zu validieren, was keinen Fehler finden konnte.

Bis übernächste Woche bin ich in Urlaub und kann nicht zeitnah auf Antworten hier reagieren. Trotzdem wollte ich das Problem bereits gemeldet haben. Sobald ich zurück bin werde ich natürlich auf Rückfragen antworten.

**Comment by XMol** [comment]
OK, sieht danach aus als hätte ich den Fehler gemacht FRST und RCUR Sequenztypen in einer Datei zu kombinieren. Getrennt lassen sich die SEPA-Dateien verarbeiten.

**Comment by rmbinder** [comment]
Ich hatte früher für´s Homebanking StarMoney. StarMoney war in der Lage, FRST und RCUR in einer Datei einzulesen. Jetzt verwende ich Jameica/Hibiscus (kostenlos). Hier muss ich getrennte Dateien für FRST und RCUR verwenden. 

Gestern erst habe ich zwei XML-Dateien (für FRST und RCUR) erstellt, mit XML-Notpad geprüft und in Jameica/Hibiscus eingelesen. Es gab keine Probleme.

**Comment by luebbe** [comment]
Ich erinnere mich, dass diese Bank stets etwas zickig mit den SEPA Dateien war und sich obendrein mit informativen Fehlermeldungen sehr zurückhielt. Fehler ließen sich nur offline mit einem XML Schema Validator finden. Auf die Idee FRST und RCUR zu kombinieren bin ich bisher nicht gekommen. Der ist mir neu.

**Comment by XMol** [comment]
Ich habe auch mit Notepad++ die kombinierte Datei erfolgreich validiert, also scheinen manche Programme und Banken in der Hinsicht einfach nicht flexibel genug zu sein.
