### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by PetraLandgraf** [rmbinder/Mitgliedsbeitrag#121]
I translated the de.xml  (version 5.1.6) to nl.xml Interested?

**Comment by rmbinder** [comment]
Yes, of course, but with the adaptation to Admidio 4.2 (which I will start soon now) some changes will come.

**Comment by rmbinder** [comment]
Sorry Petra, but I can't find a translation file. Please attach the file directly in GitHub.

**Comment by PetraLandgraf** [comment]
[nltranslation.zip](https://github.com/rmbinder/Mitgliedsbeitrag/files/10384582/nltranslation.zip)
