### ISSUE TITLE
Mitgliedsbeitrag Daten löschen

### ISSUE THREAD

**Issue by sielnet** [rmbinder/Mitgliedsbeitrag#127]
Hallo,

seit ein paar Wochen (leider kann ich nicht genau zuordnen seit wann),
dürfen Mitglieder der Vorstandsgruppe die Daten in Mitgliedsbeitrag nicht mehr löschen.
An den Rollen Einstellungen hat sich nichts geändert.
Un din den Einstellungen ist die Vorstandsrolle auch ausgewählt als "Darf auf Einstellungen zugreifen".

Ich kann zu diesem Zeitpunkt nicht sagen ob das Problem bei Admidio oder diesem Plugin liegt.
Die einzige Änderung war ein update von Admidio und Plugins seit vor den Versionen vor einem halben Jahr.

**Comment by rmbinder** [comment]
Mit Version 5.2.0 wurde das Modul "Löschen" nach "Einstellungen" verschoben, an den Zugriffseinstellungen für das Modul "Löschen" hat sich nichts geändert.
Wahrscheinlich muss die Rolle "Vorstandsgruppe" unter "Einstellungen - Zugriffsberechtigung für Einstellungen" noch eingetragen werden.

**Comment by sielnet** [comment]
Ich habe die Einstellungen geprüft.
Die Vorstandsgruppe war eingetragen.

Gerne würde ich diesen Fehler Ende Juni beheben.
Wie kann ich die Löschfunktion testen ohne die Daten wirklich zu löschen?
Wir sind mitten in der Abrechnung für das aktuelle Semester. Wir müssten entweder Warten bis Semesterende oder vielleicht ein Backup vor Tests machen.

Würde der Debug Modus von Admidio helfen um den Fehler zu finden?

**Comment by rmbinder** [comment]
_Würde der Debug Modus von Admidio helfen um den Fehler zu finden?_
Unwahrscheinlich, da nur Fehler und Warnings aufgezeichnet werden.

Sehen die Mitglieder der Vorstandsgruppe den Menüpunkt "Löschen" unter "Einstellungen"?
Wenn ja: Können sie das Modul "Löschen" auch aufrufen? (Im Modul selber wird nochmals die Berechtigung überprüft)

Zum Testen: Trage bei einem Mitglied, bei dem der Beitrag über IBAN eingezogen wurde, von Hand ein Fälligkeitsdatum ein.
Jetzt muss im Modul "Löschen" bei "Nur Fälligkeitsdatum" die Zahl 1 stehen.
Den Button "Löschen" drücken. Dadurch wird nur das vorher gesetzte Fälligkeitsdatum gelöscht.

**Comment by sielnet** [comment]
> Sehen die Mitglieder der Vorstandsgruppe den Menüpunkt "Löschen" unter "Einstellungen"?
> Wenn ja: Können sie das Modul "Löschen" auch aufrufen? (Im Modul selber wird nochmals die Berechtigung überprüft)

Dies habe ich eben getestet. Scheinbar darf das Menü für den Löschvorgang nicht aufgerufen werden. Der Eintrag dorthin (in den Einstellungen) ist sichtbar. Muss ich einen Menü Eintrag in Admidio hinzufügen für die Löschen Seite und unseren Vorstönden darauf zugriff geben?

**Comment by rmbinder** [comment]
Ich konnte den Fehler nachstellen, er sollte jetzt behoben sein.

**Comment by sielnet** [comment]
Ich habe es eben bei uns getestet und hier funktioniert es auch.
Ich wollte mich für die schnelle Behebung bedanken.
