### ISSUE TITLE
Feature: Add a table to a members profile to show "past dues" payements

### ISSUE THREAD

**Issue by Rvice** [rmbinder/Mitgliedsbeitrag#135]
We have had discrepancies with our treasurers reports making it to the roster and having this would allow us to get it in line again. There's probably two parts to this:

1. On a members profile, put a box where it contains the past contributions: "Paid Date", "Amount"
2. Another, is which "dues year" the payment is for. Our bylaws spell out when dues are owed by, but members still pay past the deadlines. Having a "dues year" in the plugin would allow us to specify the membership year they are contributing towards. This is particularly important, because some members pay in the previous year for the next year, or for multiple years.
   1. With regards to multiple years, I'm interested in thoughts on how this could be handled with the plugin. Would it set a "next payment date" to the year after they paid and record payments for the years in between? This is not currently in our bylaws, but we are exploring it.
3. Clean up bad accounting in the plugin tables. In this case, I was "testing" contributions and would like to wipe some of those out of the contribution history. I suppose I could go right to the SQL table and do this, but that's not exactly "safe"

**Comment by rmbinder** [comment]
The plugin was developed in such a way that it calculates contributions for the current club year. A SEPA XML can be generated from the calculated values, which can then be used to collect contributions. For some time now it has also been possible to add unpaid contributions to newly calculated contributions (e.g. contribution 2023 + contribution 2024). It is also possible to calculate for coming years, i.e. into the future. However, it is not possible for the plugin to fill fields that you have created yourself in the member profile.  i.e.  "Paid Date", "Amount",,. For this the entire plugin would have to be rewritten.

But:
1. The contribution history: If you work with the plugin as intended (i.e. 1. contribution calculation, 2: contribution collection, 3. set paid date), All data is in the contribution history (who paid when and how much). The history can also be exported.
  
2. Create your own profile fields and fill them yourself: Create a new profile field manually via Admidio - Preferences - Modules - Profile - Edit profile fields, e.g. "dues year". Then include this new profile field under Contribution payments in Membership fee - Preferences - View Definitions. If you now edit contribution payments, this new profile field will be displayed and you can fill it, for example "2024, 2025, 2026".

Clean up bad accounting: There is no way to delete data in history except directly in the SQL table adm_user_log. Make a backup of the entire Admidio database before.

**Comment by Rvice** [comment]
Thanks, this info is very useful. I'll give it a go and I think it'll work.
