### ISSUE TITLE
Trennzeichen für mehrere Beitragstexte

### ISSUE THREAD

**Issue by WebmasterModellflugThon** [rmbinder/Mitgliedsbeitrag#136]
Hallo,

ich verwalte die Mitglieder eines Modellflugvereins, hier gibt es jetzt Mitglieder in 2 Rollen.
Einmal Versicherung und einmal Mitgliedsbeitrag, da Mitglieder nur über den Verein versichert werden können aber nicht bei uns fliegen.
Wenn ich jetzt diese zwei Beiträge berechnen lasse sehe ich folgendes Ergebniss:
Beitragstext: AeroClub Mitgliedsbeitrag 2024 Container Miete 1 Platz

Besser wäre es wenn man für die Beitragstexte ein Trennzeichen angeben könnte: z.B. "+"
Beitragstext neu: AeroClub + Mitgliedsbeitrag 2024 + Container Miete 1 Platz

Die Trennzeicheneinstellung gibt es ja bereits für Familienmitglieder, leider aber nicht für verschiedene Rollen.

**Comment by rmbinder** [comment]
Ich habe es soeben getestet, das geht auch ohne Programmierung.

Ich habe dazu folgendes eingestellt:

1. Präfix definiert

- Mitgliedsbeitrag - Einstellungen - Beitragseinstellungen unter Präfix: AeroClub

2. Zwei neue Rollen angelegt (Die Namen der Rollen sind nicht von Bedeutung, nur die Beschreibung) 

- Erste Rolle: Name: "AeroClub Miete", Beschreibung: "+ Container Miete 1 Platz" (inkl Beitrag und Beitragszeitraum ausgefüllt)
- Zweite Rolle: Name: "AeroClub Mitgliedsbeitrag", Beschreibung: "+ Mitgliedsbeitrag 2024"  (inkl Beitrag und Beitragszeitraum ausgefüllt)

Wenn jetzt eine "Neuberechnung" durchführt wird, beginnt der Beitragstext mit "AeroClub + Mitgliedsbeitrag 2024 + Container Miete 1 Platz". Also genau das, was gefordert war.

**Comment by WebmasterModellflugThon** [comment]
Hallo, danke für die Antwort.

Prinzipiell stimme ich dir zu. Jedoch habe ich das Thema das nicht automatisch auch jedes Mitglied bei uns über den AeroClub versichert ist und dieser dann nicht im Beitragstext aufscheinen soll. Wenn das Mitglied nicht beim AeroClub ist würde der Beitragstext lauten "+ Mitgliedsbeitrag 2024 + Container Miete 1 Platz.

Anbei ein Screenshot meiner Gruppenvielfalt, hier sind fast alle unterschiedlichen kombinationen aus den Rollen möglich.
![grafik](https://github.com/rmbinder/Mitgliedsbeitrag/assets/97169504/49378e0a-ef3a-4054-a9d8-da9f4cc84068)

Ich hoffe ich konnte mein Anliegen entsprechend anbringen.

Lg

**Comment by rmbinder** [comment]
Dann bin ich von falschen Voraussetzungen ausgegangen, ich habe gedacht, Euer Verein heißt AeroClub

Ihr habt zwei Arten von Rollen: "Mitglieder von ..." und "AeroClub-Mitglied von ..". Ein Mitglied/eine Person kann Mitglied in der ersten Art ("Mitglieder von ...") sein **oder** in der zweiten Art ("AeroClub-Mitglied von ..") **oder** in beiden. Richtig? 

Zusätzlich gibt es die "Container-Rollen", wenn jemand einen Platz gemietet hat. Richtig?

**Comment by WebmasterModellflugThon** [comment]
Ja genau!

**Comment by rmbinder** [comment]
Teste mal den Branch [feature-role-names-with-delimiters](https://github.com/rmbinder/Mitgliedsbeitrag/tree/feature-role-names-with-delimiters). 
Einstellungen dazu sind in "Einstellungen - Beitragseinstellungen - Rollentrennzeichen".

**Comment by WebmasterModellflugThon** [comment]
Super, genau so habe ich es mir vorgestellt.

Funktioniert perfekt.

**Comment by rmbinder** [comment]
Ich habe den Code überarbeitet, bitte nochmal testen.

**Comment by WebmasterModellflugThon** [comment]
In meiner Testumgebung funktioniert alles wie gehabt.
Konnte nichts feststellen.
