### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by rosquillas** [rmbinder/Mitgliedsbeitrag#142]
Hello, I'm getting the following error:

"There are no contribution roles available!

Define at least one role a ’contribution’ and a ’contribution period’.

After an apparent succesful two passes of the installation process.

What am I doing wrong?

**Comment by rmbinder** [comment]
Create a new role (or modify an existing one) and enter a value for "Contribution" and "Contribution period" for this role. Now "Membership fee" recognizes this role as a "contribution role" and can work with it.

**Comment by rosquillas** [comment]
That worked, thank you.
