### ISSUE TITLE
SEPA Export SequenceType Missing

### ISSUE THREAD

**Issue by PascalTurbo** [rmbinder/Mitgliedsbeitrag#39]
When creating an export for SEPA the created xml file is not valid because the sequence Type is missing.

```
      <PmtTpInf>
        <SvcLvl>
          <Cd>SEPA</Cd>
        </SvcLvl>
        <LclInstrm>
          <Cd>CORE</Cd>
        </LclInstrm>
        <SeqTp>FRST</SeqTp>
      </PmtTpInf>
```

[http://www.onlinebanking-forum.de/forum/topic.php?t=21798&page=last#last_post](http://www.onlinebanking-forum.de/forum/topic.php?t=21798&page=last#last_post)

**Comment by rmbinder** [comment]
Membership fee v4.2.3 generates xml files in SEPA data format 3.1. New in this format is that the element group PmtTpInf can be either once in the element group PmtInf, or in each element group DrctDbtTxInf. Membership fee v4.2.3 writes them in each group DrctDbtTxInf. Look in your XML file, there is an element PmtTpInf in each DrctDbtTxInf block.

Check your home banking software. It looks like she is having trouble reading the new SEPA data format 3.1.
I import my xml files created with membership fee into StarMoney v11 and I have no problems.
