### ISSUE TITLE
Undefined index: duedatesepatype

### ISSUE THREAD

**Issue by thgibs** [rmbinder/Mitgliedsbeitrag#61]
Ich habe die Datei ausgetauscht, die Fehlermeldung kommt aber leider immer noch

**Comment by thgibs** [comment]
Ich habe die Datei ausgetauscht, die Fehlermeldung kommt aber leider immer noch

wir würde so langsam gerne unseren Einzug machen - muss ich zusätzlich noch etwas anderes austauschen, die Fehlermeldung kommt ja immer noch...

**Comment by rmbinder** [comment]
duplicate to #59 

User still used an old version of the file.
