### ISSUE TITLE
Endlosschleife nach Installation

### ISSUE THREAD

**Issue by jhartlep** [rmbinder/Mitgliedsbeitrag#64]
Moin,
zunächst einmal Danke für Dein Plugin!
Nun zum Problem:

Ich habe eine neue Installation von Admidio (Version 3.3.11) vorgenommen.
Dann habe ich Dein Plugin (Version 4.3.3) nach der Installationsanleitung zugefügt.

Wenn ich jetzt im Menü den Menüeintrag vom Plugin öffne, kommt jedes mal die Seite "Installation Mitgliedsbeitrag"

"Die Setuproutine von Mitgliedsbeitrag hat festgestellt, daß ein Versionsupdate stattgefunden hat und überprüft deshalb die Struktur."

Die Notwendigen Profilfelder werden alle als vorhanden angezeigt.
Auch auf der Folgeseite (SOLL-IST-Vergleich) ist SOLL und IST identisch.

Nach dem Klick auf Weiter lande ich dann wieder auf der Hauptseite. Und ein Klick auf den Menüeintrag (https://xxx.xxx.xxx/adm_plugins/mitgliedsbeitrag/mitgliedsbeitrag.php) führt mich wieder zur Setuproutine.

Es scheint mir, dass die Tabelle "$g_tbl_praefix.'_plugin_preferences'" beim ersten Aufruf nicht angelegt wurde. Ich finde im phpMyAdmin auch hierzu keinen Eintrag.
Auch eine Suche nach "%__Plugininformationen__version" über alle Tabellen liefert keine Ergebnisse.

Was könnte denn hier der Fehler sein?

Gruß,
Jens

**Comment by rmbinder** [comment]
Hallo Jens,

Fragen zum Plugin bitte im [Admidio-Forum](https://www.admidio.org/forum/index.php?language=de) oder als private Nachricht (auch in Admidio) stellen.

hermannhb hatte schon mal genau [dasselbe Problem](https://www.admidio.org/forum/viewtopic.php?f=10&t=8227). Ich habe einige Lösungsmöglichkeiten aufgezeigt. Sieh sie Dir mal an.

Gruß
Rainer

**Comment by jhartlep** [comment]
Hallo Rainer,
danke für die Tipps.
Mir hat letztendlich die Installation des Geburtstagslisten-Plugins geholfen.
Damit wurde die Tabelle "adm_plugin_preferences" angelegt. Danach läuft Dein Plugin.

Du solltest hier evtl. ne Prüfung bei Dir einbauen und ggf. diese Tabelle anlegen lassen bei der Installation.
