### ISSUE TITLE
table adm_plugin_preferences not created

### ISSUE THREAD

**Issue by lxnunes** [rmbinder/Mitgliedsbeitrag#65]
Hi! I have tried a fresh install of admidio (latest stable version) with this plugin (also latest stable version) and the install process described in the instructions work only untill the second pass. At that stage, after pressing "next" I come back to the initial home page without any error message.

Checking the code it seems that table adm_plugin_preferences is never created so every time I try to access mitgliedsbeitrag.php, I return to the installation.php.

If I create the table manually, all seems to work fine after I enter mitgliedsbeitrag.php

One key difference is that all my tables have a prefix, so the final name will be something like myprefixadm_plugin_preferences instead of adm_plugin_preferences. Also, I am using PHP7.3 and mariaDB 10.3.17.

Is there any way to get to see the error message or what may be happening?

regards

**Comment by rmbinder** [comment]
Hi lxnunes, 
delete this manually created table and temporarily install one of my other plugins (for example, Geburtstagsliste or Kategoriereport). These plugins use a similar installation routine and also create the ..._ plugin_preferences table. I'm trying to recreate the problem.

rmbinder

**Comment by lxnunes** [comment]
Hello rmbinder,
Workaround worked perfectly, thank you! If you need any info from my side, let me know. 
Regards
