### ISSUE TITLE
Installation page shows keys (#PLG_MITGLIEDSBEITRAG_INSTALL_TITLE#, ...) instead of texts

### ISSUE THREAD

**Issue by deki** [rmbinder/Mitgliedsbeitrag#66]
I just updated my Admidio installation to 3.3.11 and wanted to give the Mitgliedsbeitrag plugin a try. I unzipped the 4.3.3 plugin and copied it to adm_plugins. It looks like something is missing as the /mitgliedsbeitrag/installation.php page looks like this (showing #PLG_MITGLIEDSBEITRAG_INSTALL_TITLE#, ... keys instead of texts):
![mitgliedsbeitrag_screenshot](https://user-images.githubusercontent.com/858827/71557506-58dacb80-2a47-11ea-8f97-147b8ce05652.jpg)

**Comment by rmbinder** [comment]
Hello Dennis, in this [thread](https://www.admidio.org/forum/viewtopic.php?f=10&t=8110&p=29105&hilit=%23PLG_GEBURTSTAGSLISTE#p29105) I have described a workaround.

**Comment by deki** [comment]
Thanks very helpful, I was able to complete the installation.
