### ISSUE TITLE
"Krummer" Beitrag in Rolle

### ISSUE THREAD

**Issue by jhartlep** [rmbinder/Mitgliedsbeitrag#73]
Moin,
wir haben für eine Mitgliedergruppe bei uns im Verein den monatlichen Beitrag von 7,50€.
In der passenden Rolle kann ich aber nur 7€ oder 8€ angeben.
Ich habe mir aktuell damit beholfen, dass ich den Beitrag halbjährig auf 45€ gesetzt habe.
Da wir aber monatlich einziehen, ist das ziemlich unsauber.
Wie kann ich das denn anders lösen?

Danke und Gruß
Jens

**Comment by rmbinder** [comment]
Hallo Jens,
hat Du schon 7.50 probiert? (Also mit Punkt, nicht mit Komma)
Gruß
Rainer

**Comment by jhartlep** [comment]
Ja, kommt leider die gleiche Meldung, dass ich entweder 7 oder 8 eintragen muss.

**Comment by jhartlep** [comment]
Und ich habe noch etwas festgestellt:
Lt. Doku soll das hier möglich sein:
"Beitragsermäßigungen (negativer Beitrag; Mindestvorraussetzungen: Plugin-Version 4.3.2, Admidio-Version 3.3.8)"

Wenn ich als Beitrag eine Zahl < 0 eingebe, bekomme ich auch einen Fehler!

Ach ja:
Admidio Version 4.0.4, Plugin-Version 5.0.1

**Comment by rmbinder** [comment]
Der Fehler liegt nicht am Plugin, sondern an Admidio. In Admidio 3 konnte man für Rollen "krumme" Werte, auch negative, eintragen, in Admidio 4 geht das nicht mehr (Hat mich auch überrascht, wäre vielleicht mal eine Anfrage im Forum wert, ob das wieder rückgängig gemacht wird).
Man könnte jetzt entweder den Code von Admidio ändern (groupes_roles_new.php) oder versuchen, einen krummen Wert über das Plugin in eine Rolle einzutragen. 
Auf meiner Demoseite (AdmidioPluginsDemo.r-m-b.de) habe ich einer Familienrolle mal den Beitrag 100.77 zugewiesen: funktioniert

**Comment by jhartlep** [comment]
Moin,
ich habe im Forum von Admido mal eine Anfrage gestellt => https://www.admidio.org/forum/viewtopic.php?f=2&t=8733

**Comment by rmbinder** [comment]
Workaround: Admidio-Code anpassen -> groupes_roles_new.php
$form->addInput(
    'rol_cost', $gL10n->get('SYS_CONTRIBUTION').' '.$gSettingsManager->getString('system_currency'), $role->getValue('rol_cost'),
     array('type' => 'number', 'minNumber' => 0, 'maxNumber' => 99999, 'step' => 1)
);
ändern in:
$form->addInput(
    'rol_cost', $gL10n->get('SYS_CONTRIBUTION').' '.$gSettingsManager->getString('system_currency'), $role->getValue('rol_cost'),
     array('type' => 'number', 'minNumber' => -99999, 'maxNumber' => 99999, 'step' => 0.01)
);
