### ISSUE TITLE
Beitragszahlungen bearbeiten und Mandate bearbeiten produziert leere Webseite

### ISSUE THREAD

**Issue by cybertowo** [rmbinder/Mitgliedsbeitrag#74]
Die Einrichtung des PLugins habe ich erfolgreich abgeschlossen. Die Neuberechnung der Beiträge funktioniert auch, aber die Punkte "Beitragszahlungen bearbeiten" und "Mandate bearbeiten" produzieren lediglich eine leere Webseite.

Meine Admidio Version ist 4.0.3 und die Pluginversion: 5.0.1

Gruß
Thomas

**Comment by rmbinder** [comment]
Hallo Thomas,
sorry, ich hatte deinen Issue vergessen.
Funktionieren die beiden Menüpunkte mittlerweile?
Gruß
Rainer

**Comment by cybertowo** [comment]
Hallo Rainer,

ja ich habe das Problem gefunden. In den Ansichtsdefinitionen gab es Spalten, für die aber kein Datenfeld ausgewählt war. Das hat dann wohl die Datenbankabfrage durcheinander gebracht.

Gruß
Thomas
