### ISSUE TITLE
list_member function seems to misbehave somehow

### ISSUE THREAD

**Issue by Lela810** [rmbinder/Mitgliedsbeitrag#78]
[Tue Aug 03 13:22:31.430974 2021] [php7:error] [pid 115440] [client 192.168.3.110:58176] PHP Fatal error:  Uncaught Error: Call to a member function fetch() on bool in /var/www/html/adm_plugins/mitgliedsbeitrag/common_function.php:361\nStack trace:\n#0 /var/www/html/adm_plugins/mitgliedsbeitrag/payments.php(184): list_members(Array, 0, 'AND mem_usr_id ...')\n#1 {main}\n  thrown in /var/www/html/adm_plugins/mitgliedsbeitrag/common_function.php on line 361, referer: https://****************/adm_plugins/mitgliedsbeitrag/mitgliedsbeitrag.php?show_option=producemembernumber

**Comment by rmbinder** [comment]
This is not enough information for a precise error analysis. Apparently the PDO query in line 360 of the function list_members (from common_function.php) returns the value false. That it causes an error is strange because this function is used several times in the plugin.
Is this a new installation or an update?
Is there a more precise error message when the debug mode is switched on?

**Comment by Lela810** [comment]
![image](https://user-images.githubusercontent.com/71135175/128155640-21e94e5e-74fb-4180-b0f3-87958cc3c432.png)

[admidio-2021-08-04.log](https://github.com/rmbinder/Mitgliedsbeitrag/files/6930098/admidio-2021-08-04.log)

I've attached my log file and an Image of the Debug output.
Because of that Error, the payments.php is not accessible.

**Comment by rmbinder** [comment]
Go to Membership Fee - Preferences- View Definitions (Mitgliedsbeitrag - Einstellungen - Ansichtsdefinitionen) and check whether there are any entries in Columns selection (Spaltenauswahl ). To be on the safe side, save in any case.

**Comment by Lela810** [comment]
AWESOME!!!
Thank you so much!

P.S.
It works if I fill in all the Columns but by default only 5,6 and 7 are populated
![image](https://user-images.githubusercontent.com/71135175/128315941-79130950-a4af-4e2d-bf2c-3433fc77026f.png)
