### ISSUE TITLE
Calculate cents for individual cost

### ISSUE THREAD

**Issue by TobiVB** [rmbinder/Mitgliedsbeitrag#79]
Dear devs,
this plugin is quite a useful tool! However, I noticed that all cost calculation is done in integers. For membership fees, this is fine. But for some cost like electricity or water consumption, it's not precise enough. Is there an easy way to modify this from integer to float, so I can get something like 4,76€ instead of 5€?

**Comment by rmbinder** [comment]
You can use these menu items (from membership fee v5.0.2) to enter float numbers like 4.76 €:

For family roles: Preferences - Family roles (Einstellungen - Familienrollen)
For all other contributing roles: Preferences  - Advanced role editing (Einstellungen - Erweiterte Rollenbearbeitung)

**Comment by TobiVB** [comment]
Thanks. I found the issue. I was using comma as a decimal sign for "Individualbeiträge" because of German language setting. It is accepted by the input form, but then interpreted wrong. But with 4.76 € and a dot as decimal sign it works.

Maybe a hint for the input fields (tool tip) would be helpful for other users as well?

**Comment by TobiVB** [comment]
However, my question is answered. ;-)
