### ISSUE TITLE
Several white screens (Error 500) when using the module

### ISSUE THREAD

**Issue by luebbe** [rmbinder/Mitgliedsbeitrag#82]
Hi, I'm new to Admidio and I am trying to get the Mitgliedsbeitrag module to work. Most of the functions are operational, but there are some that just return a white screen. It's running on Admidio 4.1 and maybe the problems are caused by #80?

These are:
* Beiträge->Beitragszahlungen
* Mandatsverwaltung->Bearbeiten
* Export->SEPA

I'm either logged in as Admin or as a user with "Edit groups and roles" permission

**Comment by rmbinder** [comment]
The last published version of membership fee (5.0.2) is not compatible with Admidio 4.1 (membership fee version 5.1.0 will be compatible). Please use an Admidio version 4.0.x

**Comment by luebbe** [comment]
Thanks, Is it possible to downgrade from Admidio 4.1 to 4.0.x without losing the data? Are the structures still compatible?

OTOH: What needs to be done to make the module compatible with Admidio 4.1?

**Comment by rmbinder** [comment]
Downgrading will not be easy as a lot has changed in the database structure. But branch v5.1.0 (from membership fee; I'm currently working on it) is compatible with Admidio version 4.1. But be careful, not all modules work yet.

**Comment by luebbe** [comment]
OK, so I'll pull from the 5.1 branch and be your guineapig :)
Updating the membership module to 5.1 means:
- delete everything from the old module
- upload everything again from the new module
- Is there a database update/migration step from the published version to 5.1?

**Comment by rmbinder** [comment]
- delete everything from the old module --> correct
- upload everything again from the new module --> correct
- Is there a database update/migration step from the published version to 5.1? --> no, nothing has been changed in the structure

The main thing is when a member's profile is accessed via a link. In the past the user_id was passed here, now it's the user_uuid. I'm currently working on the message modules, they don't work yet.

**Comment by luebbe** [comment]
Thanks, I'll update this week and our Kassenwart and I will give it a test drive.

**Comment by olum20** [comment]
Wie ist der aktuelle Status bei diesem Thema? 
Ich habe eben Admidio 4.0.12 probiert mit 5.0.2 und hatte dort auch diese leeren Seiten.
Bis welche Version hat es funktioniert? Ich probier mal eben die 4.0.11 ...
