### ISSUE TITLE
Recalculation doesn't overwrite existing values

### ISSUE THREAD

**Issue by luebbe** [rmbinder/Mitgliedsbeitrag#85]
Steps to reproduce:
- delete membership fees
- uncheck the "partial membership fee" setting
- calculate membership fees
- check the "partial membership fee" setting
- recalculate membership fees using the overwrite option

values on which the calculation is based:
- annual membership fee is 120€
- member joined beginning of September (four months minus some days until the end of the year)

expected result:
- expected membership fee is 39€ if calculated by day or 40€ if calculated by month

observed result: 
- recalculated membership fee is still 120€

**Comment by rmbinder** [comment]
Check these settings:

- The person concerned is a member of a role with Contribution 120 € and Contribution period monthly.
- In the profile of the person concerned there is a date under Accession (e.g. 2.9.2021)
- In Membership fee under Preferences-Membership fee options there is no tick for "Calculation of proportional membership fees".

Carry out the recalculation with these settings.
For me, exactly 40 € are calculated.

**Comment by luebbe** [comment]
Some things are not clear from the description.
As far as I understand:
- Contribution fee is always annually (I didn't find this mentioned anywhere)?
- Contribution period is monthly (so admidio does the math and divides 120€/12=10€/month)?

When I do exactly that (at least I think I did) and recalculate, I receive the following result for my test member
The accession date of the member is 4.9.2021

![grafik](https://user-images.githubusercontent.com/3872576/142764057-d9981e2c-b721-4f00-a8d0-89a248eddfc0.png)

20€ dosn't make sense at all?!? It looks like the partial sum is calculated from the current date and not from the member's accession date.

![grafik](https://user-images.githubusercontent.com/3872576/142764136-f526a1d5-fd68-4222-9866-619b884067ab.png)

**Comment by rmbinder** [comment]
Take a look at the description (this is currently only available in German).

**Anteilige Beitragsberechnung**
.....
**Besonderheit Familienrollen**

Die anteilige Beitragsberechnung von Familienrollen funktioniert nach einem ähnlichen Prinzip.

- Entweder existiert eine Familienrolle bereits zu Beginn des Abrechnungsjahres (und dauert bis zum Jahresende)
- oder sie wird im Abrechnungsjahr neu angelegt (und dauert auch bis zum Jahresende).

Berechnet wird immer bis zum Jahresende, da es technisch nicht möglich ist einer Familienrolle ein Endedatum zuzuweisen (um Berechnungen von - bis durchzuführen). Ausschlaggebend für eine anteilige Berechnung bei Familienrollen ist das Datum, an dem die Rolle angelegt wurde. Dieses Datum (rol_timestamp_create) wird in Admidio nicht angezeigt und ist innerhalb von Admidio auch nicht veränderbar.

**Comment by luebbe** [comment]
Should I answer in German or keep it in English for posterity? :)
I uploaded our member list to Admidio a few weeks ago in November and could obviously create the family roles only after that date. So this means that I can't backdate the family roles to 1.1.2021?
I think it would be good to be able to have a field that contains the family roles "active start date" instead of or in addition to the role creation date.
Example: a family fills out a membership form in May, and the cashier only finds time to enter it in July. How would we handle the two months difference?

**Comment by rmbinder** [comment]
`Do I have to backdate the creation of the family to 1.1.2021 to achieve this?`

Wenn erstmalig mit Admidio (und dem Plugin Mitgliedsbeitrag) eine Beitragsberechnung durchgeführt wird, könnte man den Beitragszeitraum der Rollen auf "Jährlich" setzen (nur für das erste Jahr). Dadurch wird der gesamte Jahresbeitrag fällig, unabhängig vom Datum an dem eine Rolle angelegt wurde.

Für die Zukunft mache ich mir mal Gedanken, ob ich eine Möglichkeit schaffen könnte, das Datum, an dem eine Rolle angelegt wurde ((rol_timestamp_create) vom Plugin aus zu verändern. Wird aber etwas dauern, da ich zur Zeit damit beschäftigt bin, alle meine Plugins (und ich bin erst beim Dritten) kompatibel für Admidio 4.1 zu machen.

**Comment by rmbinder** [comment]
Ich löse das Problem jetzt anders -> #89

**Comment by luebbe** [comment]
Prima, danke. Dann bin ich mal gespannt, wann ich Admidio+Plugins auf die neueste Version hieven kann.
