### ISSUE TITLE
Member links in recalculation link to wrong profile

### ISSUE THREAD

**Issue by luebbe** [rmbinder/Mitgliedsbeitrag#86]
Steps to reproduce:
- Start a recalculation
- Click on a member's name
- Look at your own profile

The link to the member doesn't contain a uuid. I guess that this is the reason:
`https://<meinverein>.de/adm_program/modules/profile/profile.php?user_uuid=`

**Comment by rmbinder** [comment]
The user_uuid was only introduced with Admidio 4.1. You are using a plugin version that is not suitable for Admidio 4.1.

**Comment by luebbe** [comment]
I've updated my install to the 5.1 dev branch a few days ago. Since you're working on compatibility I wanted to let you know

**Comment by rmbinder** [comment]
#80
