### ISSUE TITLE
 Internal Server Errors (500) on Paid membership fees

### ISSUE THREAD

**Issue by Rvice** [rmbinder/Mitgliedsbeitrag#87]
Admidio 4.0.11
Mitgliedsbeitrag: 5.0.2

When I go to the Paid membership fees and select one of the Roles and click "Process membership payments" I get error 500.
![image](https://user-images.githubusercontent.com/1831523/145081733-594da2b8-1c21-4e7e-a417-bc97ea5b52a7.png)
Result:
![image](https://user-images.githubusercontent.com/1831523/145081936-17005c63-e211-4979-887f-a3fd7e9154a0.png)

Is there any error logs to check? I tried the adm_my_files/logs, but nothing is there

**Comment by rmbinder** [comment]
That should be the same mistake as described [here](https://github.com/rmbinder/Mitgliedsbeitrag/issues/84). There is an issue and a workaround (in the issue). It will be fixed in the next version of the plugin.

**Comment by rmbinder** [comment]
#84
