### ISSUE TITLE
Fresh installation of this plugin doesnt work

### ISSUE THREAD

**Issue by piggeldi** [rmbinder/Mitgliedsbeitrag#92]
I started a new setup of Admidio on a fresh installed system. Admidio itself works without problems. No problem so far. 

However, when adding the membership fee plugin I get stuck in "Installation membership fee", no matter how many times I click on "continue" nothing happens. 

I find the following error in the Apache error.log: 

```
Thu Jan 13 10:45:39.826912 2022] [php7:notice] [pid 14653] [client 192.168.178.47:53861] PHP Notice:  Trying to get property 'cat_id' of non-object in /var/www/html/adm_plugins/mitgliedsbeitrag/installation.php on line 1414, referer: http://admidio/adm_plugins/mitgliedsbeitrag/installation.php
```

Admidio-Version: 4.1.2
Mitgliedsbeitrag-Version: 5.0.2

I also made sure that the Apache user in the www directory is always **www-data**. 

EDIT 1: Im using the chrome browser

Thanks for your help and hints :)!

**Comment by rmbinder** [comment]
Membership fee v5.0.2 is not compatible with Admidio 4.1.2. Please use membership fee v5.1.0.

**Comment by piggeldi** [comment]
@rmbinder Thanks for this super quick answer. I got a bit confused between the official admidio website and github. Everything works now!
