### ISSUE TITLE
Abrechnungsperioden

### ISSUE THREAD

**Issue by idnovic** [rmbinder/Mitgliedsbeitrag#94]
Wir wurden gerne die Abrechnung alle 6 Monate machen. 
Allerdings jeweils vom 
1.4.22 - 30.9.22 und 1.10.22 - 31.3.23

Wird das unterstützt oder würde das Plugin durcheinander kommen?

Was müsste ich am Code ändern, damit die Perioden stimmen?

**Comment by rmbinder** [comment]
Geht es nur darum, 2x im Jahr eine Abrechnung durchzuführen?
Habt Ihr auch anteilige Beiträge? (Also wenn jemand zum 01.06. eintritt. Muss er dann den vollen Beitrag 1.4. bis 30.9 zahlen oder nur für 4 Monate?)
Habt Ihr auch Beiträge aufgrund des Alters?

**Comment by idnovic** [comment]
Ja wir wollen 2 mal im Jahr eine Abrechnung durchführen. Unsere Beiträge sind eigentlich monatlich. Allerdings ziehen wir im Voraus ein. Also Anfang April für 1.4.-30.9.
Deswegen ist die Abrechnung halbjährlich. 

Anteilige Beiträge gibt es in den Sinne, das 
wir nur die "genutzten" Monate abrechnen. Also ja, wenn jemand am 1.5. beitritt, wird 1.4.-30.4. nicht gezahlt, sondern nur 1.5.-30.9.. Verlässt jemand den Verein, erhält die Person nicht genutzte Monate wieder (das macht aber die Buchhaltung, ist keine Voraussetzung für Admidio). 

Wir Staffeln nicht nach Alter. 

Wir haben 2 Beiträge. 
Einen Mitgliedschaftsbeitrag. (zahlen alle)
Eine Gebühr zur Internetnutzung. (zahlen die meisten)

Ich habe dies so eingestellt, dass es 2 Gruppen gibt welche jeweils eine Gebühr eingestellt haben. Die meisten Mitglieder sollen Teil beider Gruppen werden. 

Es gibt auch Ehrenmitglieder, bei denen habe ich eingestellt, dass sie einen Rabatt in Höhe von X haben. Diese zahlen dann wegen der Gruppenzugehörigkeit nichts. 


Wenn es Möglich ist, die aktuell von mir erstellten Gruppen, Abhängigkeit und Preise zu exportieren, würde ich diese durch einem privaten Kanal teilen. Falls dies hilft.

**Comment by rmbinder** [comment]
Mitgliedsbeitrag kann eine anteilige monatliche Beitragsberechnung durchführen (wie bei Euch, die "genutzten" Monate), also wenn jemand zum 1.5. dem Verein beitritt, braucht er nur die Monate Mai bis Dez. bezahlen. 

Dies geht aber nur für das aktuelle Abrechnungsjahr, also von Jan. bis Dez., nicht für diesen "Versatz" zweites/drittes und viertes/erstes Quartal.

Derzeit bin ich am Überlegen, ob ich den "Stichtag" abschaffe und den damit verbundenen Vorgang automatisiere. Vielleicht wirkt sich das auch auf die "Abrechnungsperioden" aus.

**Comment by idnovic** [comment]
Okay verstehe. Vielen Dank.  Ich würde mich über eine Lösung wie Sie es vorgeschlagen haben freuen. 

Wenn ich den Stichtag (Tag an dem die Gebühren gezahlt werden müssen?) auf den 1.2.21 einstellen würde und eine halbjährliche Abrechnung eingestellt habe, sollte doch vom Plugin zurück gerechnet werden. Weil 6 Monate. Oder was genau passiert? In diesem Beispiel sollte das Plugin dann vom 1.10.20-28.2.21 abrechnen. Zumindest wäre das meine Erwartung. 

Wir sind halt hauptsächlich Student:innen. 
Deswegen der Versatz. 

Frage zur anteiligen monatlich Berechnung:
Erfolg die Berechnung an Hand von der Anzahl der Tage? Also wenn eine Person am 16.4. dem Verein beitritt, Wird eine Gebühr vom 16.4.-30.4. anteilig berechnet?


Anderes Thema, beim Testen ist mir aufgefallen, dass ich Rechnungen nur für Mitglieder ohne Bankverbindung erstellen darf. Für die Buchhaltung wäre es super, wenn eine vollständige Abrechnung als PDF exportiert werden kann. Also auch für die Mitglieder welche per Sepa gebucht werden.

Noch eine Frage bezieht sich auf die Ausschluss Einstellungen. Was bewirkt es genau, einzelne Gruppen bei der Abrechnung voneinander auszuschließen?

Wenn es okay ist, würde ich später ein Bild schicken und die aktuell eingestellten Abhängigkeiten bei der Abrechnung beschreiben. Wäre super wenn Sie kurz drüber schauen könnten und mir sagen ob das so funktioniert oder Probleme möglich wären.

**Comment by rmbinder** [comment]
**Stichtag**
Der "Stichtag" hat nur Auswirkungen auf die altersgestaffelten Rollen (passt das Mitglied am Stichtag noch in eine altersgestaffelte Rolle oder muss es in eine andere verschoben werden?). Er hat also nur indirekten Einfluß auf die Beitragsberechnung (den "Stichtag" will ich aber, wie bereits geschrieben, streichen).

**anteilige monatliche Berechnung**
ein Auszug aus der Dokumentation:
 * Für die anteilige Berechnung bei Beendigung der Mitgliedschaft wird das Ende einer Rollenzugehörigkeit verwendet.
  * Für die anteilige Berechnung bei Beginn einer Mitgliedschaft wird, je nach Konfiguration, entweder das Beitrittsdatum oder der Beginn einer Rollenmitgliedschaft verwendet.

  * Beitragszeitraum Monatlich: Berechnet wird jeder angefangene Monat
    * Bsp: Beitritt im April -> Berechnet werden Apr bis Dez = 9 Monate = 9/12 vom Jahresbeitrag
    * Bsp: Austritt im Juni  -> Berechnet werden Jan bis Jun = 6 Monate = 6/12 vom Jahresbeitrag

**Rechnungen nur für Mitglieder**
Dazu über "Gruppen & Rollen- Listen bearbeiten" eine eigene Liste erstellen. Auf alle Fälle das Feld "Beitrag" einbinden und hier als Bedingung "<>0" eingeben.

**Ausschluss Einstellungen**
ein Auszug aus der Dokumentation:
Hinweis: Die Prüfungen haben keinen Einfluss auf die Beitragsberechnung. Sie dienen, wie der Name schon sagt, nur zur Prüfung bestimmter Daten.
Das soll im Prinzip dazu dienen, zu erkennen, ob jemand z.B. gleichzeitig in einer altersgestaffelten Rolle und in einer Familienrolle ist. Was evtl. nicht sein darf, sich also ausschließen soll (weil ansonsten doppelter Beitrag berechnet wird).

**Comment by idnovic** [comment]
Kontoinhaber:
bei uns sind die Kontoinhaber meistens die Mitglieder selbst. Allerdings brauchen wir die Adresse des Mitgliedes nicht, weil wir die Zimmernummer im Studentenwohnheim kennen. Bei der Buchhaltung wäre allerdings die Heimatadresse relevant. 

Ich habe es jetzt so eingestellt, dass bei jedem Mitglied bei der Registrierung  separat Kontoinhaber und Bankdaten eingegeben werden müssen. Obwohl es meistens eine Person ist. 

Gibt es Probleme bei der Abrechnung, wenn es in Wahrheit die selbe Person ist?
Zur Klarstellung, jedes Mitglied hat keine eigenen Kontodaten eingestellt, sondern separat einen Kontobevollmächtigten. Nur ist es meistens die selbe Person.

**Comment by idnovic** [comment]
Danke furs Beantworten meiner vielen Fragen!

**Comment by rmbinder** [comment]
**zu Kontoinhaber:**
Bei den Kontodaten muss im Prinzip nur die IBAN vorhanden sein.

Wenn aber im Feld Kontoinhaber etwas eingetragen wird, dann geht das Plugin davon aus, dass Kontoinhaber und Mitglied nicht identisch sind und will weitere Informationen des Kontoinhabers (wie Straße, Ort usw.). Welche Daten hier jetzt eingeben werden ist aber egal, die Felder dürfen nur nicht leer sein.

Für die SEPA-XML-Datei werden mindestens folgende Informationen benötigt: Mandatsdatum, Mandats-ID, IBAN, Betrag, Verwendungszweck und Kontoinhaber

Wenn das Feld Kontoinhaber (im Profil im Abschnitt Kontodaten) jetzt ausgefüllt ist, werden diese Angaben für die XML-Datei verwendet. Wenn es leer ist, wird der Name des Kontoinhabers zusammengesetzt aus Vor- und Zuname des Mitglieds. Also an die Bank gesendet wird nur die IBAN und der Name des Kontoinhabers, kein Ort, keine Straße, keine Tel.Nr. 

**einen anderen Zeitraum berechnen:**
Wenn der Jahresbeitrag 100€ wäre, könnte man in einer Rolle als Beitrag 50€ (Beitragszeitraum jährlich) eingeben. Bei der anschließenden Berechnung werden 50 € errechnet. In einem halben Jahr dasselbe Spiel von vorne. Wie man hier dann aber eine anteilige Berechnung einbringen könnte, muss ich mir erst nochmal überlegen.

**Comment by idnovic** [comment]
Okay macht Sinn. 
Wir arbeiten mit Einzugsdatum in den Verein und Kündigungsdatum. Die aktuelle Logik bei Admidio kennt soweit ich das gesehen habe gar kein Kündigungsdatum. 
Für uns ist aber das Einzugsdatum wichtig. 
Für uns würde der Beginn einer Rollenmitgliedschaft nur bedingt funktionieren. Ließe sich aber mit zwei Gruppen für jeweils Mitgliedschaft und Internetnutzung bewerkstelligen. 
Ich habe nun eingestellt, dass neue Mitglieder automatisch teil der Gruppe sind. 

Kündigungsdatum ist nicht so relevant für Admidio. Die Differenz und Erstattung kann die Buchhaltung berechnen. 

Wäre natürlich schön wenn die Abrechnung einen Zeitraum angegeben hat. 
Allerdings können wir auch den Sepa Betreff ändern jedes halbe Jahr. 

Aktuell habe ich eine halbjährige Abrechnung eingestellt. Passend zu einem Semester.

**Comment by luebbe** [comment]
Bisher war es bei uns mit den Abrechnungsperioden einfach. Einmal, zu Jahresbeginn wurden die Beiträge eingezogen/die Rechnung gestellt. Wer im Laufe des Jahres hinzukommt, zahlt anteilig für den Rest des Jahres.
Hier gab es unter anderem die Komplikation, dass z.B. durch neu hinzugekommene Geschwister/Eltern, mitten im Jahr der Familienbeitrag attraktiver wird, als die Einzelbeiträge und wir das dann umstellen. Geht momentan nur mit selber nachrechnen, ist aber nicht schlimm.
Jetzt ist jemand hinzugekommen, der partout den Beitrag für sein Kind quartalsweise per Dauerauftrag überweisen will. D.h. dafür müsste ich wohl eine neue Rolle definieren, um diese Sonderregelung abzubilden?

**Comment by rmbinder** [comment]
@luebbe:
So einen Fall hatte ich auch mal. Ich habe dazu eine Rolle mit dem Namen "Selbstzahler" (Beitrag 0 €, Beitragszeitraum jährlich) erstellt. Einziges Mitglied in dieser Rolle war dann das Kind, dessen Eltern direkt (bar) zahlten/überwiesen. 

Damit das Kind im ganzen System erfasst wurde (also auch in den Abrechnungen/Auswertungen als Beitragszahler) habe ich die Prüfungen entsprechend angepasst: Unter "Rollenmitgliedschaft (Pflicht)" gab es dann folgende (mit Haken markierte) Rollen: Altersgestaffelte Rollen, Familienrollen, Ehrenmitglieder, einige Festbeitragsrollen und diese Rolle Selbstzahler. Unter "Rollenmitgliedschaft (Ausschluss)" habe ich dann entsprechend ausgewählt, dass z.B. ein Ehrenmitglied nicht gleichzeitig Selbstzahler sein darf, usw usw.

**Comment by luebbe** [comment]
Danke @rmbinder, das ist ein guter Hinweis. Ich richte das mal so ein und kläre unseren Kassierer entsprechend auf. Eigentlich könnte ich dieser "Selbstzahler" Rolle ja schon einen Beitrag zuweisen. Warum nicht 1/4 des Jahresbeitrags, Zeitraum vierteljährlich? Oder kommt das dann Admidio in die Quere, weil es Exports für die Rechnung erstellen möchte?
Wir haben auch ein paar Mitglieder, deren Beitrag vom Sozialamt über Gutscheine übernommen wird, die die Mitglieder bei uns abgeben und die unser Kassierer dann beim Sozialamt einreicht. Vielleicht sollte ich das ähnlich handhaben? Bisher laufen die mit dem normalen Beitrag unter Rechnung.

**Comment by rmbinder** [comment]
"1/4 des Jahresbeitrags, Zeitraum vierteljährlich" hört sich verständlich an, aber das Plugin Mitgliedsbeitrag ist anders aufgebaut. Der Beitrag ist immer der Jahresbeitrag und der Beitragszeitraum wird verwendet für die anteilige Beitragsberechnung. Das passt so nicht.

Besser wäre es, den zu zahlenden Jahresbeitrag als Beitrag in der Rolle zu setzen und als Beitragszeitraum jährlich. Dann Beitrag berechnen und einziehen. Danach neues Fälligkeitsdatum setzen und nochmals einziehen, usw. 

Aber warum?
Es muss doch kein Einzug stattfinden und somit auch keine XML-Datei erzeugt werden.  Es sollte doch reichen, wenn der Kassierer eine Liste erhält mit Daten von Personen, bei denen der Beitrag nicht eingezogen wird, sondern die von selbst zahlen oder einen Gutschein bringen.

**Comment by luebbe** [comment]
OK, hoffentlich bekomme ich das:
1. in meinen Kopf und
2. heute Abend dazu, das einzurichten. Gestern war Training :)

Ich kämpfe gedanklich immer noch mit den Konzepten. Klar gibt es keinen XML Einzug und der Kassierer braucht eine Liste der Rechnungszahler sowie der Sonderfälle.
Benötiche ich dann für jeden Selbstzahler mit individuellem Intervall und jeweiligem Beitrag eine neue Rolle?
D.h. Selbstzahler Jugend 1/4 jährlich, Selbstzahler Senioren jährlich, Selbstzahler Jugend jährlich etc.? Die Beiträge an sich bleiben ja gleich. 
Letzendlich müsste man den Selbstzahlern ja auch bestätigen, dass die Zahlung eingegangen ist. Oder sie erinnern, wenn sie es vergessen haben. Was weniger Arbeit macht. Wahrscheinlich erinnern, weil es selten vorkommt.

**Comment by idnovic** [comment]
> OK, hoffentlich bekomme ich das:
> 
> 1. in meinen Kopf und
> 2. heute Abend dazu, das einzurichten. Gestern war Training :)
> 
> Ich kämpfe gedanklich immer noch mit den Konzepten. Klar gibt es keinen XML Einzug und der Kassierer braucht eine Liste der Rechnungszahler sowie der Sonderfälle. Benötiche ich dann für jeden Selbstzahler mit individuellem Intervall und jeweiligem Beitrag eine neue Rolle? D.h. Selbstzahler Jugend 1/4 jährlich, Selbstzahler Senioren jährlich, Selbstzahler Jugend jährlich etc.? Die Beiträge an sich bleiben ja gleich. Letzendlich müsste man den Selbstzahlern ja auch bestätigen, dass die Zahlung eingegangen ist. Oder sie erinnern, wenn sie es vergessen haben. Was weniger Arbeit macht. Wahrscheinlich erinnern, weil es selten vorkommt.

Ich würde es mit Abhängigkeiten versuchen. Vorschlag:
Gruppe "Jugend" ist automatisch Mitglied von "Selbstzahler"
Gruppe "Senioren" ist automatisch Mitglied von "Selbstzahler"
Bei den Einstellungen von der Gruppe "Selbstzahler" lässt sich das einstellen. 

Nun den Preis bei Selbstzahler einstellen. 
Den Rabatt in der anderen Gruppe als Differenz mit minus davor (erweiterte Einstellungen beim Buchhaltungsmodul). 

Wir haben keine Altersstaffelung aber ich konnte so aus Teilgebühren für unsere Mitglieder jeweils das richtige berechnen lassen. Muss aber hinzufügen, ich teste das alles noch. Gibt nur wenige freiwillige Tester.

**Comment by idnovic** [comment]
> "1/4 des Jahresbeitrags, Zeitraum vierteljährlich" hört sich verständlich an, aber das Plugin Mitgliedsbeitrag ist anders aufgebaut. Der Beitrag ist immer der Jahresbeitrag und der Beitragszeitraum wird verwendet für die anteilige Beitragsberechnung. Das passt so nicht.
> 
> Besser wäre es, den zu zahlenden Jahresbeitrag als Beitrag in der Rolle zu setzen und als Beitragszeitraum jährlich. Dann Beitrag berechnen und einziehen. Danach neues Fälligkeitsdatum setzen und nochmals einziehen, usw.
> 

Wenn ich einen Beitragszeitraum jährlich einstellen würde. Was passiert wenn ich 2 mal im selben Jahr dieses Beitrag einziehe?

Ich hätte angenommen: Erster Einzug Jahr 2021, Zweiter Einzug Jahr 2022. Weil das Plugin weiß, Jahr 2021 wurde schon gezahlt. 

Oder Ignoriert das Plugin das Datum völlig und geht immer von einem vollen Jahr aus? Mit dem Unterschied dass das Beitrittsdatum für anteilige Berechnung genutzt wird. 


Wenn das so ist, würde es ja reichen wenn das Plugin einen von mir eingestellten Zeitraum versteht. Solange dieser 12 Monate hat. 

Unsere nächste Abrechnung ist Anfang April. Bisher sieht bei den Tests alles gut aus (6 monatige Zyklen). Ich bin mir nur unsicher was das Plugin im Oktober berechnen würde. 
Meine Annahme ist, es berechnet Okt-Dez und damit 3 anstatt 6 Monate wie Okt-März.

**Comment by rmbinder** [comment]
Ich habe mich bei der Entwicklung des Plugins an meinem Verein orientiert mit folgenden Vorgaben:

- Alle Mitgliedsbeiträge sind Jahresbeiträge
- Die Mitgliedsbeiträge werden einmal im Jahr eingezogen
- Der Beitragseinzug findet immer zum 01.04. eines Jahres statt 
- Die Beitragsberechnung dazu erfolgt etwa in der ersten Märzwoche.
- Wer während des Jahres eintritt, dem wird der Mitgliedsbeitrag anteilig berechnet. (Eintritt im Juli, dann 6/12 des Jahresbeitrages)
- Ausschlaggebend für eine anteilige Beitragsberechnung ist das Beitrittsdatum (aufgrund einer Anfrage im Forum kann hier auch der Beginn der Mitgliedschaft in einer Rolle eingestellt werden)

 
In Admidio kann man für eine Rolle einen Beitrag und einen Beitragszeitraum definieren. Der Beitrag ist eben der zu zahlende Beitrag (und zwar immer als Jahresbeitrag gesehen), die Einstellung für Beitragszeitraum verwende ich aber für die Berechnung des anteiligen Beitrages. NICHT dafür, wie oft ein Beitrag im Jahr eingezogen wird. In der Dokumentation habe ich das Ganze ausführlich erläutert.

- Nehmen wir mal an, wir möchten 2x im Jahr einen Beitrag einziehen. (Das Plugin ist jetzt zwar nicht dafür ausgelegt, aber vielleicht ist es ja doch möglich. Wir betrachten aber nur bestehende Mitglieder, nicht die, die während des Jahres beitreten). 
- Der Jahresbeitrag soll 100 € sein.

- Wir legen eine Rolle an mit Beitrag 50 € und Beitragszeitraum jährlich (jährlich bedeutet in diesem Fall, dass keine anteilige Berechnung durchgeführt wird; es werden bei jeder Berechnung immer 50 € fällig). 
- Wir führen eine ganz normale Beitragsberechnung durch. Das Ergebnis ist, dass jedes Mitglied 50 € zahlen muss.
- Wir vergeben ein Fälligkeitsdatum, erzeeugen die SEPA-XML-Datei und ziehen den Beitrag ein.
- Wenn die Beiträge eingezogen sind, setzen wir den Marker "Bezahlt-Datum". (Dadurch wird das Fälligkeitsdatum, der Beitrag, der Beitragstext usw gelöscht; ein FRST wird zu RCUR)
- Wenn der zweite Beitrag ansteht (nach 6 Monaten), führen wird erneut eine Beitragsberechnung durch. 
- Es werden wieder je Mitglied 50 € errechnet.
- Jetzt wieder Fälligkeitsdatum setzen, XML-Datei erzeugen und Beitrag einziehen.

Somit hätten wir im Endeffekt 100 € auf 2x eingezogen.

Dem Plugin ist es im Prinzip egal, wann ein Beitrag bezahlt wurde. Es muss bzw. sollte immer (nach erfolgtem Bankeinzug) der Marker "Bezahlt-Datum" gesetzt werden. Das Setzen dieses Datum ist der Trigger für einige Folgeereignisse (z.B. FRST wird zu RCUR).
