### ISSUE TITLE
leere Seite Beitragszahlungen

### ISSUE THREAD

**Issue by mikkamm** [rmbinder/Mitgliedsbeitrag#98]
Nachdem Klick auf Beitragszahlungen bearbeiten erscheint eine leere Seite. Im Debugmodus erscheint folgender Fehler:

S Q L - E R R O R

CODE: 42000
1064

You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AS '86', .usd_value AS '90', .usd_value AS '89', .usd_value AS '87', LAST_NAM...' at line 1

B A C K T R A C E

FILE: adm_program/system/classes/Database.php
LINE: 689
CALL: Database->showError()

FILE: adm_plugins/mitgliedsbeitrag/common_function.php
LINE: 355
CALL: Database->queryPrepared()

FILE: adm_plugins/mitgliedsbeitrag/payments.php
LINE: 187
CALL: list_members()

**Comment by rmbinder** [comment]
Dieser Fehler sollte eigentlich seit der Version 5.1.0 des Plugins behoben sein (#84).
Welche Version von Mitgliedsbeitrag wird denn verwendet?

**Comment by mikkamm** [comment]
Ich habe es mit der Versionen 5.0.2 und 5.1.1 ausprobiert. Bei beiden habe ich das gleiche Problem.

**Comment by rmbinder** [comment]
In Einstellungen-Ansichtsdefinitionen muss bei Spaltenauswahl bei allen Spalten unter Inhalt ein Profilfeld eingetragen sein.
Sind hier noch weiße Felder sichtbar?

**Comment by mikkamm** [comment]
Ja, hier sind die ersten 4 Spalten nicht belegt. Kann ich hier einfach eine Auswahl treffen oder müssen hier default Werte eingetragen werden?

**Comment by rmbinder** [comment]
Einfach irgendetwas eintragen. Diese Felder dürfen nicht leer sein.
Wie ich bereits geschrieben habe, dürfte dieser Fehler seit der Version 5.1.0 nicht mehr auftreten. Ich habe auch noch eine extra "Sicherung" mit eingebaut, dass diese leeren Felder (falls sie doch noch vorhanden sind) herausfiltert.

**Comment by mikkamm** [comment]
Danke. Anscheinend war der Browsercache das Problem
