### ISSUE TITLE
Sepa Pre Notice Error 500

### ISSUE THREAD

**Issue by idnovic** [rmbinder/Mitgliedsbeitrag#99]
Ich habe versucht eine Pre Notice per Email an 2 Mitglieder zu versenden. 

Sobald ich auf"Abschicken" klicke, komme ich auf eine leere Seite und nichts passiert. 
Ein Mal wurde mir Error 500 angezeigt. 

Wie kann ich den Fehler rausfinden?

**Comment by rmbinder** [comment]
In adm_my_files\config.php `$gDebug=1` setzen. Dadurch werden Fehlermeldungen am Bildschirm angezeigt.

**Comment by idnovic** [comment]
Danke!

Ich hatte bisher keine Zeit es wieder zu testen. Gebe die Tage Rückmeldung.

**Comment by rmbinder** [comment]
Im Forum wurde vom selben Fehler berichtet: [https://www.admidio.org/forum/viewtopic.php?f=10&t=9168](https://www.admidio.org/forum/viewtopic.php?f=10&t=9168)
Mit Version 5.1.2 sollte er behoben sein.
